import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // Improves performance
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
     <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased scroll-smooth min-h-screen bg-gradient-to-br from-blue-500 via-purple-500 to-purple-600 suppressHydrationWarning`  }
      >
        {children}
      </body>
    </html>
  );
}
